### ISSUE TITLE
Twitter アカウント作成画面（※必須）

### ISSUE THREAD

**Issue by y-iwamoto** [y-iwamoto/twitter-cloneapp#3]
ユーザを登録させるための、アカウント作成画面を作成。
"呼び名","電話番号"または"メールアドレス","パスワード"を入力し、
アカウント作成ボタンを押下する事で、ユーザデータを登録させ、自分のマイページに遷移させる予定。
エラーチェックについては、本家 Twitterでは、リアルタイムバリデーションになっているため、クローンでもリアルタイムバリデーションを考慮してみる予定。

**Comment by NaitoYuki** [comment]
@y-iwamoto 
issues/#3にのブランチに対してプルリクエストをお願いします。

**Comment by NaitoYuki** [comment]
クローズします。
